Create DATABASE hw1;
USE hw1;


CREATE TABLE ACCOUNTS (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    SURNAME VARCHAR(50) NOT NULL,
    USERNAME VARCHAR(20) NOT NULL UNIQUE,
    EMAIL VARCHAR(40) NOT NULL UNIQUE,
    PASSWORD VARCHAR(60) NOT NULL
);

CREATE TABLE FAVOURITES (
    ID INTEGER PRIMARY KEY,
    USER INTEGER NOT NULL,
    CONTENT JSON
);